0a1,4
> # Adapted from https://github.com/ray-project/ray/blob/ray-1.10.0/python/ray/_private/metrics_agent.py
> # Fixed the problem in https://github.com/skypilot-org/skypilot/issues/990, by adding exception catch for creating the metrics agent.
> # The change is adapted from https://github.com/ray-project/ray/blob/ray-1.13.0/python/ray/_private/metrics_agent.py#L77-L95
> 
74,79c78,87
<         self.view_manager.register_exporter(
<             prometheus_exporter.new_stats_exporter(
<                 prometheus_exporter.Options(
<                     namespace="ray",
<                     port=metrics_export_port,
<                     address=metrics_export_address)))
---
>         try:
>             stats_exporter = prometheus_exporter.new_stats_exporter(
>                     prometheus_exporter.Options(
>                         namespace="ray",
>                         port=metrics_export_port,
>                         address=metrics_export_address))
>         except Exception:
>             self.view_manager = None
>         else:
>             self.view_manager.register_exporter(stats_exporter)
