{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b2071116-35e6-4785-a480-5f7bd67af07f",
   "metadata": {},
   "source": [
    "# Tour of Sky\n",
    "Sky is a tool to run any workload seamlessly across different cloud providers through a unified interface. No knowledge of cloud offerings is required or expected - you simply define the workload and its resource requirements, and Sky will automatically execute it on AWS, Google Cloud Platform or Microsoft Azure.\n",
    "\n",
    "### Key Features\n",
    "- **Run your code on the cloud with zero code changes**\n",
    "- **Easy provisionioning of VMs** across multiple cloud platforms (AWS, Azure or GCP)\n",
    "- **Fast and iterative development** with quick access to cloud instances for prototyping. If cloud is unavailable, a local development mode is also available\n",
    "- **Store your datasets on the cloud** and access them like you would on a local filesystem\n",
    "- **No cloud lock-in** - easily move your code from Azure GPUs to Google TPUs with one line change"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "4cc2ad6a-6f8a-43ae-879e-81847c0f12a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# TODO: make this pip install sky\n",
    "# pip install -e ..\n",
    "import os\n",
    "import tempfile"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7a0869f9-7227-4825-a818-0656a8e673b7",
   "metadata": {},
   "source": [
    "## Hello, Sky!\n",
    "We can specify the following task attributes with a YAML file:\n",
    "- `resources` (optional): what cloud resources the task must be run on (e.g. accelerators, instance type, etc.)\n",
    "- `setup` (optional): commands that must be run before the task is executed\n",
    "- `run`: specifies the commands that must be run as the actual ask"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "2ec1c8a8-59b5-4277-86df-cd4ee980f62e",
   "metadata": {},
   "outputs": [],
   "source": [
    "hello_sky_spec = \"\"\"\n",
    "resources:\n",
    " cloud: aws\n",
    " accelerators: K80\n",
    "\n",
    "setup: |\n",
    " echo \"running setup\"\n",
    "\n",
    "run: |\n",
    " echo \"hello sky!\"\n",
    " ping localhost -c 5\n",
    "\"\"\"\n",
    "\n",
    "with tempfile.NamedTemporaryFile('w', prefix='sky_tour-', delete=False) as fp:\n",
    "    fp.write(hello_sky_spec)\n",
    "    fp.flush()\n",
    "    os.environ[\"SKY_SPEC\"] = fp.name"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eafb8a31-3c50-4662-8adf-3ce0c4e15c07",
   "metadata": {},
   "source": [
    "Sky handles selecting an appropriate cluster size based on user-specified resource constraints, launching the cluster on an appropriate cloud provider, and executing the task. \n",
    "\n",
    "To launch a task based on our above YAML spec, we can use `sky launch`. The `-c` option allows us to specify a cluster name. If a cluster with that name already exists (which can be viewed with `sky status`), Sky will re-use that cluster. If no such cluster exists, a new cluster with that name will be provisioned. If no cluster name is provided (e.g. `sky launch task.yaml`), then a cluster name will be autogenerated."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "119c5e5f-d2a9-4f57-aa48-459ab550f2d1",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mFile Mount: (/tmp/setup.sh:/tmp/sky_setup_2521886668.sh) refers to a file.\n",
      " To ensure this mount updates properly, please use a directory.\u001b[39m\n",
      "2022-01-13 23:10:31,931\tINFO util.py:282 -- setting max workers for head node type to 0\n",
      "Checking AWS environment settings\n",
      "Destroying cluster. \u001b[4mConfirm [y/N]:\u001b[24m y \u001b[2m[automatic, due to --yes]\u001b[22m\n",
      "\u001b[33mFile Mount: (/tmp/setup.sh:/tmp/sky_setup_2521886668.sh) refers to a file.\n",
      " To ensure this mount updates properly, please use a directory.\u001b[39m\n",
      "2022-01-13 23:10:33,504\tINFO util.py:282 -- setting max workers for head node type to 0\n",
      "\u001b[33mLoaded cached provider configuration\u001b[39m\n",
      "\u001b[33mIf you experience issues with the cloud provider, try re-running the command with \u001b[1m--no-config-cache\u001b[22m\u001b[26m.\u001b[39m\n",
      "\u001b[37mFetched IP\u001b[39m: \u001b[1m18.220.133.95\u001b[22m\n",
      "Warning: Permanently added '18.220.133.95' (ECDSA) to the list of known hosts.\n",
      "\u001b[32mStopped all 14 Ray processes.\u001b[39m\n",
      "\u001b[0mShared connection to 18.220.133.95 closed.\n",
      "Requested \u001b[1m1\u001b[22m\u001b[26m nodes to shut down.\u001b[0m\u001b[2m [interval=1s]\u001b[22m\u001b[0m\n",
      "\u001b[1m0\u001b[22m\u001b[26m nodes remaining after 5 second(s).\n",
      "\u001b[32mNo nodes remaining.\u001b[39m\n",
      "\u001b[0m\u001b[32mTerminating cluster mycluster...done.\u001b[0m\n",
      "\u001b[0m\u001b[34mDetected YAML file: /tmp/sky_tour-u76bp__4\u001b[0m\n",
      "\u001b[33mRunning task on cluster mycluster ...\u001b[0m\n",
      "I 01-13 23:10:45 execution.py:83] Optimizer target is set to COST.\n",
      "I 01-13 23:10:45 optimizer.py:208] Defaulting estimated time to 1 hr. Call Task.set_time_estimator() to override.\n",
      "I 01-13 23:10:45 optimizer.py:307] Optimizer - plan minimizing cost (~$0.9):\n",
      "I 01-13 23:10:45 optimizer.py:321] \n",
      "I 01-13 23:10:45 optimizer.py:321] TASK                                  BEST_RESOURCE\n",
      "I 01-13 23:10:45 optimizer.py:321] Task(run='echo \"hello sky!\"\\np...')   AWS(p2.xlarge)\n",
      "I 01-13 23:10:45 optimizer.py:321]   resources: {AWS(None, {'K80': 1})}\n",
      "I 01-13 23:10:45 optimizer.py:321] \n",
      "I 01-13 23:10:45 cloud_vm_ray_backend.py:993] \u001b[36mCreating a new cluster: \"mycluster\" [1x AWS(p2.xlarge)].\u001b[0m\n",
      "I 01-13 23:10:45 cloud_vm_ray_backend.py:993] Tip: to reuse an existing cluster, specify --cluster-name (-c) in the CLI or use sky.launch(.., cluster_name=..) in the Python API. Run `sky status` to see existing clusters.\n",
      "I 01-13 23:10:45 cloud_vm_ray_backend.py:624] To view detailed progress: \u001b[1mtail -n100 -f sky_logs/sky-2022-01-13-23-10-45-182615/provision.log\u001b[0m\n",
      "I 01-13 23:10:45 cloud_vm_ray_backend.py:634] \n",
      "I 01-13 23:10:45 cloud_vm_ray_backend.py:634] \u001b[1mLaunching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f)\u001b[0m\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Collecting ray[default]==1.9.2\n",
      "  Downloading ray-1.9.2-cp36-cp36m-manylinux2014_x86_64.whl (57.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 57.6 MB 11 kB/s s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: protobuf>=3.15.3 in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (3.18.1)\n",
      "Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (5.4.1)\n",
      "Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (1.19.5)\n",
      "Collecting grpcio>=1.28.1\n",
      "  Downloading grpcio-1.43.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.1 MB 31.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting click>=7.0\n",
      "  Downloading click-8.0.3-py3-none-any.whl (97 kB)\n",
      "\u001b[K     |████████████████████████████████| 97 kB 176 kB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting msgpack<2.0.0,>=1.0.0\n",
      "  Downloading msgpack-1.0.3-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (299 kB)\n",
      "\u001b[K     |████████████████████████████████| 299 kB 44.6 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting dataclasses\n",
      "  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)\n",
      "Collecting redis>=3.5.0\n",
      "  Downloading redis-4.1.0-py3-none-any.whl (171 kB)\n",
      "\u001b[K     |████████████████████████████████| 171 kB 45.9 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: attrs in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (21.2.0)\n",
      "Collecting filelock\n",
      "  Downloading filelock-3.4.1-py3-none-any.whl (9.9 kB)\n",
      "Requirement already satisfied: jsonschema in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (3.2.0)\n",
      "Collecting colorful\n",
      "  Downloading colorful-0.5.4-py2.py3-none-any.whl (201 kB)\n",
      "\u001b[K     |████████████████████████████████| 201 kB 60.0 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting aiohttp>=3.7\n",
      "  Downloading aiohttp-3.8.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.1 MB 57.9 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (2.26.0)\n",
      "Collecting py-spy>=0.2.0\n",
      "  Downloading py_spy-0.3.11-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 3.0 MB 54.2 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: prometheus-client>=0.7.1 in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (0.11.0)\n",
      "Collecting opencensus\n",
      "  Downloading opencensus-0.8.0-py2.py3-none-any.whl (128 kB)\n",
      "\u001b[K     |████████████████████████████████| 128 kB 56.3 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting frozenlist\n",
      "  Downloading frozenlist-1.2.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (191 kB)\n",
      "\u001b[K     |████████████████████████████████| 191 kB 51.6 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting smart-open\n",
      "  Downloading smart_open-5.2.1-py3-none-any.whl (58 kB)\n",
      "\u001b[K     |████████████████████████████████| 58 kB 8.2 MB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting aiohttp-cors\n",
      "  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)\n",
      "Collecting aioredis<2\n",
      "  Downloading aioredis-1.3.1-py3-none-any.whl (65 kB)\n",
      "\u001b[K     |████████████████████████████████| 65 kB 863 kB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting gpustat>=1.0.0b1\n",
      "  Downloading gpustat-1.0.0b1.tar.gz (82 kB)\n",
      "\u001b[K     |████████████████████████████████| 82 kB 305 kB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting aiosignal\n",
      "  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)\n",
      "Collecting asynctest==0.13.0\n",
      "  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)\n",
      "Collecting async-timeout<5.0,>=4.0.0a3\n",
      "  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)\n",
      "Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp>=3.7->ray[default]==1.9.2) (2.0.6)\n",
      "Collecting idna-ssl>=1.0\n",
      "  Downloading idna-ssl-1.1.0.tar.gz (3.4 kB)\n",
      "Collecting multidict<7.0,>=4.5\n",
      "  Downloading multidict-5.2.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (159 kB)\n",
      "\u001b[K     |████████████████████████████████| 159 kB 52.5 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.6/dist-packages (from aiohttp>=3.7->ray[default]==1.9.2) (3.10.0.2)\n",
      "Collecting yarl<2.0,>=1.0\n",
      "  Downloading yarl-1.7.2-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (270 kB)\n",
      "\u001b[K     |████████████████████████████████| 270 kB 50.8 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting hiredis\n",
      "  Downloading hiredis-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl (84 kB)\n",
      "\u001b[K     |████████████████████████████████| 84 kB 265 kB/s  eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from click>=7.0->ray[default]==1.9.2) (4.8.1)\n",
      "Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.6/dist-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (1.16.0)\n",
      "Collecting nvidia-ml-py3>=7.352.0\n",
      "  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)\n",
      "Collecting psutil\n",
      "  Downloading psutil-5.9.0-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (279 kB)\n",
      "\u001b[K     |████████████████████████████████| 279 kB 58.6 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting blessed>=1.17.1\n",
      "  Downloading blessed-1.19.0-py2.py3-none-any.whl (57 kB)\n",
      "\u001b[K     |████████████████████████████████| 57 kB 7.8 MB/s  eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.6/dist-packages (from blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]==1.9.2) (0.2.5)\n",
      "Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.6/dist-packages (from idna-ssl>=1.0->aiohttp>=3.7->ray[default]==1.9.2) (3.2)\n",
      "Collecting packaging>=21.3\n",
      "  Downloading packaging-21.3-py3-none-any.whl (40 kB)\n",
      "\u001b[K     |████████████████████████████████| 40 kB 554 kB/s  eta 0:00:01\n",
      "\u001b[?25hCollecting deprecated>=1.2.3\n",
      "  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.6/dist-packages (from deprecated>=1.2.3->redis>=3.5.0->ray[default]==1.9.2) (1.12.1)\n",
      "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->click>=7.0->ray[default]==1.9.2) (3.6.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging>=21.3->redis>=3.5.0->ray[default]==1.9.2) (2.4.7)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/dist-packages (from jsonschema->ray[default]==1.9.2) (0.18.0)\n",
      "Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from jsonschema->ray[default]==1.9.2) (58.2.0)\n",
      "Collecting opencensus-context==0.1.2\n",
      "  Downloading opencensus_context-0.1.2-py2.py3-none-any.whl (4.4 kB)\n",
      "Collecting google-api-core<3.0.0,>=1.0.0\n",
      "  Downloading google_api_core-2.4.0-py2.py3-none-any.whl (111 kB)\n",
      "\u001b[K     |████████████████████████████████| 111 kB 54.2 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting contextvars\n",
      "  Downloading contextvars-2.4.tar.gz (9.6 kB)\n",
      "Collecting google-auth<3.0dev,>=1.25.0\n",
      "  Downloading google_auth-2.3.3-py2.py3-none-any.whl (155 kB)\n",
      "\u001b[K     |████████████████████████████████| 155 kB 52.0 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting googleapis-common-protos<2.0dev,>=1.52.0\n",
      "  Downloading googleapis_common_protos-1.54.0-py2.py3-none-any.whl (207 kB)\n",
      "\u001b[K     |████████████████████████████████| 207 kB 54.2 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (4.7.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (0.2.1)\n",
      "Collecting cachetools<5.0,>=2.0.0\n",
      "  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->ray[default]==1.9.2) (2021.5.30)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->ray[default]==1.9.2) (1.26.7)\n",
      "Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from rsa<5,>=3.1.4->google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (0.4.8)\n",
      "Collecting immutables>=0.9\n",
      "  Downloading immutables-0.16-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (103 kB)\n",
      "\u001b[K     |████████████████████████████████| 103 kB 53.0 MB/s eta 0:00:01\n",
      "\u001b[?25hBuilding wheels for collected packages: gpustat, idna-ssl, nvidia-ml-py3, contextvars\n",
      "  Building wheel for gpustat (setup.py) ... done\n",
      "\u001b[?25h  Created wheel for gpustat: filename=gpustat-1.0.0b1-py3-none-any.whl size=15979 sha256=8ccf7c6d6b6d73c94fbd9e894ba8ccff89d93e3a6b5ccde765db9f4888fd2769\n",
      "  Stored in directory: /home/ubuntu/.cache/pip/wheels/e1/00/ea/3d99aba74443fdf01e3bcabccdde3529b9d0b582b24a6c017a\n",
      "  Building wheel for idna-ssl (setup.py) ... done\n",
      "\u001b[?25h  Created wheel for idna-ssl: filename=idna_ssl-1.1.0-py3-none-any.whl size=3178 sha256=8240bb38b1d285894a97400c7f6f642e458a3e1df8fb2f7f25ca167bcb96aa6a\n",
      "  Stored in directory: /home/ubuntu/.cache/pip/wheels/6a/f5/9c/f8331a854f7a8739cf0e74c13854e4dd7b1af11b04fe1dde13\n",
      "  Building wheel for nvidia-ml-py3 (setup.py) ... done\n",
      "\u001b[?25h  Created wheel for nvidia-ml-py3: filename=nvidia_ml_py3-7.352.0-py3-none-any.whl size=19191 sha256=88bfef28c7b3f6790bbff4213b99d8d88e7818d76395e688355d209ab02658d5\n",
      "  Stored in directory: /home/ubuntu/.cache/pip/wheels/7f/26/a3/33f2079871e2bebb3f53a2b21c3ec64129b8efdd18a6263a52\n",
      "  Building wheel for contextvars (setup.py) ... done\n",
      "\u001b[?25h  Created wheel for contextvars: filename=contextvars-2.4-py3-none-any.whl size=7680 sha256=3cbb23711706c42e97ba5d4d34ec4630456d3ca145d715b0b773554cc25c85e8\n",
      "  Stored in directory: /home/ubuntu/.cache/pip/wheels/41/11/53/911724983aa48deb94792432e14e518447212dd6c5477d49d3\n",
      "Successfully built gpustat idna-ssl nvidia-ml-py3 contextvars\n",
      "Installing collected packages: multidict, immutables, frozenlist, cachetools, yarl, packaging, idna-ssl, googleapis-common-protos, google-auth, deprecated, contextvars, asynctest, async-timeout, aiosignal, redis, psutil, opencensus-context, nvidia-ml-py3, msgpack, hiredis, grpcio, google-api-core, filelock, dataclasses, click, blessed, aiohttp, smart-open, ray, py-spy, opencensus, gpustat, colorful, aioredis, aiohttp-cors\n",
      "\u001b[33m  WARNING: The scripts ray, ray-operator, rllib, serve and tune are installed in '/home/ubuntu/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\n",
      "\u001b[33m  WARNING: The script gpustat is installed in '/home/ubuntu/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\n",
      "Successfully installed aiohttp-3.8.1 aiohttp-cors-0.7.0 aioredis-1.3.1 aiosignal-1.2.0 async-timeout-4.0.2 asynctest-0.13.0 blessed-1.19.0 cachetools-4.2.4 click-8.0.3 colorful-0.5.4 contextvars-2.4 dataclasses-0.8 deprecated-1.2.13 filelock-3.4.1 frozenlist-1.2.0 google-api-core-2.4.0 google-auth-2.3.3 googleapis-common-protos-1.54.0 gpustat-1.0.0b1 grpcio-1.43.0 hiredis-2.0.0 idna-ssl-1.1.0 immutables-0.16 msgpack-1.0.3 multidict-5.2.0 nvidia-ml-py3-7.352.0 opencensus-0.8.0 opencensus-context-0.1.2 packaging-21.3 psutil-5.9.0 py-spy-0.3.11 ray-1.9.2 redis-4.1.0 smart-open-5.2.1 yarl-1.7.2\n",
      "\u001b[33mWARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Collecting pendulum\n",
      "  Downloading pendulum-2.1.2-cp36-cp36m-manylinux1_x86_64.whl (154 kB)\n",
      "\u001b[K     |████████████████████████████████| 154 kB 22.0 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting PrettyTable\n",
      "  Downloading prettytable-2.5.0-py3-none-any.whl (24 kB)\n",
      "Collecting pytzdata>=2020.1\n",
      "  Downloading pytzdata-2020.1-py2.py3-none-any.whl (489 kB)\n",
      "\u001b[K     |████████████████████████████████| 489 kB 47.2 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: python-dateutil<3.0,>=2.6 in /usr/local/lib/python3.6/dist-packages (from pendulum) (2.8.2)\n",
      "Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from PrettyTable) (0.2.5)\n",
      "Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from PrettyTable) (4.8.1)\n",
      "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil<3.0,>=2.6->pendulum) (1.16.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->PrettyTable) (3.6.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->PrettyTable) (3.10.0.2)\n",
      "Installing collected packages: pytzdata, PrettyTable, pendulum\n",
      "Successfully installed PrettyTable-2.5.0 pendulum-2.1.2 pytzdata-2020.1\n",
      "\u001b[33mWARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.\n",
      "You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\n",
      "\u001b[0mrunning setup\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Requirement already satisfied: boto3>=1.4.8 in /usr/local/lib/python2.7/dist-packages (1.17.112)\n",
      "Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.4.8) (0.10.0)\n",
      "Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.4.8) (0.4.2)\n",
      "Requirement already satisfied: botocore<1.21.0,>=1.20.112 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.4.8) (1.20.112)\n",
      "Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == \"2.7\" in /usr/local/lib/python2.7/dist-packages (from s3transfer<0.5.0,>=0.4.0->boto3>=1.4.8) (3.3.0)\n",
      "Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python2.7/dist-packages (from botocore<1.21.0,>=1.20.112->boto3>=1.4.8) (2.8.2)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python2.7/dist-packages (from botocore<1.21.0,>=1.20.112->boto3>=1.4.8) (1.26.7)\n",
      "Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.21.0,>=1.20.112->boto3>=1.4.8) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Did not find any active Ray processes.\n",
      "\u001b[0mbash: ulimit: open files: cannot modify limit: Operation not permitted\n",
      "\u001b[37mLocal node IP\u001b[39m: \u001b[1m172.31.60.142\u001b[22m\n",
      "2022-01-13 23:14:06,948\tINFO services.py:1340 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "\n",
      "\u001b[32m--------------------\u001b[39m\n",
      "\u001b[32mRay runtime started.\u001b[39m\n",
      "\u001b[32m--------------------\u001b[39m\n",
      "\n",
      "\u001b[36mNext steps\u001b[39m\n",
      "  To connect to this Ray runtime from another node, run\n",
      "  \u001b[1m  ray start --address='172.31.60.142:6379' --redis-password='5241590000000000'\u001b[22m\n",
      "  \n",
      "  Alternatively, use the following Python code:\n",
      "    \u001b[31mimport\u001b[39m\u001b[26m ray\n",
      "    ray\u001b[31m.\u001b[39m\u001b[26minit(address\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'auto'\u001b[39m\u001b[26m, _redis_password\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'5241590000000000'\u001b[39m\u001b[26m)\n",
      "  \n",
      "  To connect to this Ray runtime from outside of the cluster, for example to\n",
      "  connect to a remote cluster from your laptop directly, use the following\n",
      "  Python code:\n",
      "    \u001b[31mimport\u001b[39m\u001b[26m ray\n",
      "    ray\u001b[31m.\u001b[39m\u001b[26minit(address\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'ray://<head_node_ip_address>:10001'\u001b[39m\u001b[26m)\n",
      "  \n",
      "  \u001b[4mIf connection fails, check your firewall settings and network configuration.\u001b[24m\n",
      "  \n",
      "  To terminate the Ray runtime, run\n",
      "  \u001b[1m  ray stop\u001b[22m\n",
      "\u001b[0mCluster: mycluster\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "\n",
      "File Mount: (/tmp/setup.sh:/tmp/sky_setup_2521886668.sh) refers to a file.\n",
      " To ensure this mount updates properly, please use a directory.\n",
      "Checking AWS environment settings\n",
      "AWS config\n",
      "  IAM Profile: ray-autoscaler-v1 [default]\n",
      "  EC2 Key pair (all available node types): sky-key-61ef58\n",
      "  VPC Subnets (all available node types): subnet-fca11d9a, subnet-822893a3, subnet-9dcd81d0, subnet-254bf27a, subnet-1a78b82b, subnet-cb92e4c5 [default]\n",
      "  EC2 Security groups (all available node types): sg-0cd6f7480591cd6ad [default]\n",
      "  EC2 AMI (all available node types): ami-0e3c68b57d50caf64\n",
      "\n",
      "No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]\n",
      "\n",
      "Acquiring an up-to-date head node\n",
      "  create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient p2.xlarge capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get p2.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c, us-east-1d, us-east-1e., retrying.\n",
      "  create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient p2.xlarge capacity in the Availability Zone you requested (us-east-1b). Our system will be working on provisioning additional capacity. You can currently get p2.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1c, us-east-1d, us-east-1e., retrying.\n",
      "  create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient p2.xlarge capacity in the Availability Zone you requested (us-east-1c). Our system will be working on provisioning additional capacity. You can currently get p2.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1d, us-east-1e., retrying.\n",
      "  create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient p2.xlarge capacity in the Availability Zone you requested (us-east-1d). Our system will be working on provisioning additional capacity. You can currently get p2.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1e., retrying.\n",
      "  Launched 1 nodes [subnet_id=subnet-1a78b82b]\n",
      "    Launched instance i-0a9ae425f8260dff1 [state=pending, info=pending]\n",
      "  Launched a new head node\n",
      "  Fetching the new head node\n",
      "  \n",
      "<1/1> Setting up head node\n",
      "  Prepared bootstrap config\n",
      "  New status: waiting-for-ssh\n",
      "  [1/7] Waiting for SSH to become available\n",
      "    Running `uptime` as a test.\n",
      "    Waiting for IP\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Received: 18.214.89.219\n",
      "    SSH still not available (SSH command failed.), retrying in 5 seconds.\n",
      "    SSH still not available (SSH command failed.), retrying in 5 seconds.\n",
      "    SSH still not available (SSH command failed.), retrying in 5 seconds.\n",
      "    SSH still not available (SSH command failed.), retrying in 5 seconds.\n",
      "    SSH still not available (SSH command failed.), retrying in 5 seconds.\n",
      "    Success.\n",
      "  Updating cluster configuration. [hash=70049628df139b57b5dd30f9a65a6514a422604b]\n",
      "  New status: syncing-files\n",
      "  [2/7] Processing file mounts\n",
      "    ~/.sky/remote_libs/ from /home/ubuntu/sky/prototype/sky/backends/remote_libs/\n",
      "    /tmp/setup.sh from /tmp/sky_setup_2521886668.sh\n",
      "  [3/7] No worker file mounts to sync\n",
      "  New status: setting-up\n",
      "  [4/7] No initialization commands to run.\n",
      "  [5/7] Initalizing command runner\n",
      "  [6/7] Running setup commands\n",
      "    (0/4) pip3 install -U ray[default]==...\n",
      "    (1/4) pip3 install pendulum PrettyTa...\n",
      "    (2/4) cd ~/sky_workdir && bash /tmp/...\n",
      "    (3/4) pip install 'boto3>=1.4.8'\n",
      "  [7/7] Starting the Ray runtime\n",
      "  New status: up-to-date\n",
      "\n",
      "Useful commands\n",
      "  Monitor autoscaling with\n",
      "    ray exec /home/ubuntu/sky/prototype/config/user/mycluster.yml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'\n",
      "  Connect to a terminal on the cluster head:\n",
      "    ray attach /home/ubuntu/sky/prototype/config/user/mycluster.yml\n",
      "  Get a remote shell to the cluster manually:\n",
      "    ssh -o IdentitiesOnly=yes -i ~/.ssh/sky-key ubuntu@18.214.89.219\n",
      "I 01-13 23:14:08 cloud_vm_ray_backend.py:700] \u001b[1mSuccessfully provisioned or found existing VM. Setup completed.\u001b[0m\n",
      "I 01-13 23:14:08 cloud_vm_ray_backend.py:703] \n",
      "I 01-13 23:14:08 cloud_vm_ray_backend.py:703] To log into the head VM:\t\u001b[1mssh mycluster\u001b[0m\n",
      "I 01-13 23:14:08 cloud_vm_ray_backend.py:703] \n",
      "I 01-13 23:14:12 cloud_vm_ray_backend.py:1253] Reserved Job ID: 1\n",
      "I 01-13 23:14:14 cloud_vm_ray_backend.py:1220] Job submitted with Job ID: \u001b[1m1\u001b[0m\n",
      "\u001b[33mStart streaming logs...\u001b[0m\n",
      "SKY INFO: Reserving task slots on 1 nodes.\n",
      "SKY INFO: All task slots reserved.\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m hello sky!\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m PING localhost (127.0.0.1) 56(84) bytes of data.\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m 64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.053 ms\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m 64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.038 ms\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m 64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.036 ms\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m 64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.036 ms\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m 64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.060 ms\n",
      "Shared connection to 18.214.89.219 closed.\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m \n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m --- localhost ping statistics ---\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m 5 packets transmitted, 5 received, 0% packet loss, time 4084ms\n",
      "\u001b[2m\u001b[36m(task pid=3876)\u001b[0m rtt min/avg/max/mdev = 0.036/0.044/0.060/0.012 ms\n",
      "\u001b[0mI 01-13 23:14:23 cloud_vm_ray_backend.py:1228] NOTE: ctrl-c does not stop the job.\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1228] \n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1228] \u001b[36mJob ID: \u001b[1m1\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1228] To cancel the job:\t\u001b[1msky cancel -c mycluster 1\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1228] To stream the logs:\t\u001b[1msky logs -c mycluster 1\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1228] To view the job queue:\t\u001b[1msky queue mycluster\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1375] \n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1375] \u001b[36mCluster name: \u001b[1mmycluster\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1375] To log into the head VM:\t\u001b[1mssh mycluster\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1375] To submit a job:\t\t\u001b[1msky exec -c mycluster yaml_file\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1375] To stop the cluster:\t\u001b[1msky stop mycluster\u001b[0m\n",
      "I 01-13 23:14:23 cloud_vm_ray_backend.py:1375] To teardown the cluster:\t\u001b[1msky down mycluster\u001b[0m\n",
      "Sky Clusters\n",
      "+-----------------+-------------+--------------------+------------------------------------------------+--------+\n",
      "|       NAME      |   LAUNCHED  |     RESOURCES      | COMMAND                                        | STATUS |\n",
      "+-----------------+-------------+--------------------+------------------------------------------------+--------+\n",
      "|   test-github   |  17 hrs ago | 1x AWS(m4.2xlarge) | sky cpunode -c test-github                     |   UP   |\n",
      "| sky-bbbd-ubuntu | 13 mins ago | 1x AWS(m4.2xlarge) | sky launch /tmp/sky_tour-h_z1hu1m              |   UP   |\n",
      "|    mycluster    | 14 secs ago | 1x AWS(p2.xlarge)  | sky launch -c mycluster /tmp/sky_tour-u76bp__4 |   UP   |\n",
      "+-----------------+-------------+--------------------+------------------------------------------------+--------+\n",
      "\u001b[0m\u001b[0m"
     ]
    }
   ],
   "source": [
    "!sky launch -c mycluster $SKY_SPEC"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "050aeda1-87dc-4e46-acde-2f8c04c4c003",
   "metadata": {},
   "source": [
    "We can see above that our task executed by printing \"hello sky!\" and by pinging localhost 5 times. We can also view `sky status` to see that a new cluster named `mycluster` was created on AWS."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "52e04a56-c48b-4d91-8e37-4ab50a31cca2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sky Clusters\n",
      "+-----------------+-------------+--------------------+------------------------------------------------+--------+\n",
      "|       NAME      |   LAUNCHED  |     RESOURCES      | COMMAND                                        | STATUS |\n",
      "+-----------------+-------------+--------------------+------------------------------------------------+--------+\n",
      "|   test-github   |  17 hrs ago | 1x AWS(m4.2xlarge) | sky cpunode -c test-github                     |   UP   |\n",
      "| sky-bbbd-ubuntu | 13 mins ago | 1x AWS(m4.2xlarge) | sky launch /tmp/sky_tour-h_z1hu1m              |   UP   |\n",
      "|    mycluster    | 51 secs ago | 1x AWS(p2.xlarge)  | sky launch -c mycluster /tmp/sky_tour-u76bp__4 |   UP   |\n",
      "+-----------------+-------------+--------------------+------------------------------------------------+--------+\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!sky status"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f3004b67-3b9d-47f9-aac6-232a3b867456",
   "metadata": {},
   "source": [
    "## Training a Language Model on TPU"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "755aac2a-619f-482b-a6cd-fe93248539ac",
   "metadata": {},
   "outputs": [],
   "source": [
    "lm_spec = \"\"\"\n",
    "resources:\n",
    "  accelerators: tpu-v3-8\n",
    "  accelerator_args:\n",
    "    tf_version: 2.5.0\n",
    "\n",
    "setup: |\n",
    "  pip install --upgrade pip\n",
    "\n",
    "  conda activate huggingface\n",
    "  if [ $? -eq 0 ]; then\n",
    "    echo 'conda env exists'\n",
    "  else\n",
    "    conda create -n huggingface python=3.8 -y\n",
    "    conda activate huggingface\n",
    "    pip install -r requirements.txt\n",
    "  fi\n",
    "\n",
    "run: |\n",
    "  conda activate huggingface\n",
    "  python -u run_tpu.py\n",
    "\"\"\"\n",
    "\n",
    "with tempfile.NamedTemporaryFile('w', prefix='sky_tour-', delete=False) as fp:\n",
    "    fp.write(lm_spec)\n",
    "    fp.flush()\n",
    "    os.environ[\"SKY_SPEC\"] = fp.name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "019d38a1-d760-481d-bd29-e35a0ce97e3e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34mDetected YAML file: /tmp/sky_tour-5gxbi87d\u001b[0m\n",
      "I 01-14 00:04:41 resources.py:56] Missing tpu_name in accelerator_args, using default (sky_tpu)\n",
      "\u001b[33mRunning task on cluster sky-b1d1-ubuntu ...\u001b[0m\n",
      "I 01-14 00:04:41 execution.py:83] Optimizer target is set to COST.\n",
      "I 01-14 00:04:41 optimizer.py:208] Defaulting estimated time to 1 hr. Call Task.set_time_estimator() to override.\n",
      "I 01-14 00:04:41 optimizer.py:307] Optimizer - plan minimizing cost (~$8.5):\n",
      "I 01-14 00:04:41 optimizer.py:321] \n",
      "I 01-14 00:04:41 optimizer.py:321] TASK                                                                                                         BEST_RESOURCE\n",
      "I 01-14 00:04:41 optimizer.py:321] Task(run='conda activate huggi...')                                                                          GCP(n1-highmem-8, {'tpu-v3-8': 1}, accelerator_args={'tf_version': '2.5.0', 'tpu_name': 'sky_tpu'})\n",
      "I 01-14 00:04:41 optimizer.py:321]   resources: {None(None, {'tpu-v3-8': 1}, accelerator_args={'tf_version': '2.5.0', 'tpu_name': 'sky_tpu'})}\n",
      "I 01-14 00:04:41 optimizer.py:321] \n",
      "I 01-14 00:04:41 cloud_vm_ray_backend.py:624] To view detailed progress: \u001b[1mtail -n100 -f sky_logs/sky-2022-01-14-00-04-41-378449/provision.log\u001b[0m\n",
      "I 01-14 00:04:41 cloud_vm_ray_backend.py:634] \n",
      "I 01-14 00:04:41 cloud_vm_ray_backend.py:634] \u001b[1mLaunching on GCP us-central1 (us-central1-a)\u001b[0m\n",
      "I 01-14 00:04:43 cloud_vm_ray_backend.py:592] TPU sky_tpu already exists; skipped creation.\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "2022-01-14 00:04:55,314\tINFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1642118694683-5d57f8d79c238-2095deca-4e851ed9 to finish...\n",
      "2022-01-14 00:05:00,673\tINFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1642118694683-5d57f8d79c238-2095deca-4e851ed9 finished.\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "2022-01-14 00:05:05,877\tINFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1642118705327-5d57f8e1c2f03-caa05bfe-9d2de04d to finish...\n",
      "2022-01-14 00:05:11,284\tINFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1642118705327-5d57f8e1c2f03-caa05bfe-9d2de04d finished.\n",
      "Requirement already satisfied: ray[default]==1.9.2 in /opt/conda/lib/python3.7/site-packages (1.9.2)\n",
      "Requirement already satisfied: redis>=3.5.0 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (4.1.0)\n",
      "Requirement already satisfied: pyyaml in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (6.0)\n",
      "Requirement already satisfied: numpy>=1.16 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (1.19.5)\n",
      "Requirement already satisfied: grpcio>=1.28.1 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (1.43.0)\n",
      "Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (8.0.3)\n",
      "Requirement already satisfied: jsonschema in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (4.3.1)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (1.0.3)\n",
      "Requirement already satisfied: protobuf>=3.15.3 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (3.19.1)\n",
      "Requirement already satisfied: attrs in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (21.2.0)\n",
      "Requirement already satisfied: filelock in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (3.4.2)\n",
      "Requirement already satisfied: py-spy>=0.2.0 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (0.3.11)\n",
      "Requirement already satisfied: aioredis<2 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (1.3.1)\n",
      "Requirement already satisfied: gpustat>=1.0.0b1 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (1.0.0b1)\n",
      "Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (2.26.0)\n",
      "Requirement already satisfied: aiohttp-cors in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (0.7.0)\n",
      "Requirement already satisfied: frozenlist in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (1.2.0)\n",
      "Requirement already satisfied: colorful in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (0.5.4)\n",
      "Requirement already satisfied: opencensus in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (0.8.0)\n",
      "Requirement already satisfied: prometheus-client>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (0.12.0)\n",
      "Requirement already satisfied: smart-open in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (5.2.1)\n",
      "Requirement already satisfied: aiosignal in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (1.2.0)\n",
      "Requirement already satisfied: aiohttp>=3.7 in /opt/conda/lib/python3.7/site-packages (from ray[default]==1.9.2) (3.8.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (1.7.2)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4 in /opt/conda/lib/python3.7/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (4.0.1)\n",
      "Requirement already satisfied: asynctest==0.13.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (0.13.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.7/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (5.2.0)\n",
      "Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (2.0.9)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /opt/conda/lib/python3.7/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (4.0.1)\n",
      "Requirement already satisfied: hiredis in /opt/conda/lib/python3.7/site-packages (from aioredis<2->ray[default]==1.9.2) (2.0.0)\n",
      "Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from click>=7.0->ray[default]==1.9.2) (4.9.0)\n",
      "Requirement already satisfied: blessed>=1.17.1 in /opt/conda/lib/python3.7/site-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (1.19.0)\n",
      "Requirement already satisfied: six>=1.7 in /opt/conda/lib/python3.7/site-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (1.16.0)\n",
      "Requirement already satisfied: nvidia-ml-py3>=7.352.0 in /opt/conda/lib/python3.7/site-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (7.352.0)\n",
      "Requirement already satisfied: psutil in /opt/conda/lib/python3.7/site-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (5.8.0)\n",
      "Requirement already satisfied: packaging>=21.3 in /opt/conda/lib/python3.7/site-packages (from redis>=3.5.0->ray[default]==1.9.2) (21.3)\n",
      "Requirement already satisfied: deprecated>=1.2.3 in /opt/conda/lib/python3.7/site-packages (from redis>=3.5.0->ray[default]==1.9.2) (1.2.13)\n",
      "Requirement already satisfied: importlib-resources>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema->ray[default]==1.9.2) (5.4.0)\n",
      "Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema->ray[default]==1.9.2) (0.18.0)\n",
      "Requirement already satisfied: opencensus-context==0.1.2 in /opt/conda/lib/python3.7/site-packages (from opencensus->ray[default]==1.9.2) (0.1.2)\n",
      "Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from opencensus->ray[default]==1.9.2) (2.3.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->ray[default]==1.9.2) (2021.10.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->ray[default]==1.9.2) (1.26.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->ray[default]==1.9.2) (3.1)\n",
      "Requirement already satisfied: wcwidth>=0.1.4 in /opt/conda/lib/python3.7/site-packages (from blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]==1.9.2) (0.2.5)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in /opt/conda/lib/python3.7/site-packages (from deprecated>=1.2.3->redis>=3.5.0->ray[default]==1.9.2) (1.13.3)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (59.6.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (1.53.0)\n",
      "Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (2.3.3)\n",
      "Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->click>=7.0->ray[default]==1.9.2) (3.6.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.7/site-packages (from packaging>=21.3->redis>=3.5.0->ray[default]==1.9.2) (3.0.6)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (0.2.7)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (4.2.4)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (4.8)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (0.4.8)\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "Requirement already satisfied: pendulum in /opt/conda/lib/python3.7/site-packages (2.1.2)\n",
      "Requirement already satisfied: PrettyTable in /opt/conda/lib/python3.7/site-packages (2.4.0)\n",
      "Requirement already satisfied: pytzdata>=2020.1 in /opt/conda/lib/python3.7/site-packages (from pendulum) (2020.1)\n",
      "Requirement already satisfied: python-dateutil<3.0,>=2.6 in /opt/conda/lib/python3.7/site-packages (from pendulum) (2.8.2)\n",
      "Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from PrettyTable) (4.9.0)\n",
      "Requirement already satisfied: wcwidth in /opt/conda/lib/python3.7/site-packages (from PrettyTable) (0.2.5)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil<3.0,>=2.6->pendulum) (1.16.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->PrettyTable) (3.6.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->PrettyTable) (4.0.1)\n",
      "\u001b[0mRequirement already satisfied: pip in /opt/conda/lib/python3.7/site-packages (21.3.1)\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "conda env exists\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "Collecting google-api-python-client==1.7.8\n",
      "  Downloading google_api_python_client-1.7.8-py3-none-any.whl (56 kB)\n",
      "     |████████████████████████████████| 56 kB 3.0 MB/s             \n",
      "\u001b[?25hRequirement already satisfied: six<2dev,>=1.6.1 in /opt/conda/lib/python3.7/site-packages (from google-api-python-client==1.7.8) (1.16.0)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.0.3 in /opt/conda/lib/python3.7/site-packages (from google-api-python-client==1.7.8) (0.1.0)\n",
      "Requirement already satisfied: google-auth>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from google-api-python-client==1.7.8) (2.3.3)\n",
      "Collecting uritemplate<4dev,>=3.0.0\n",
      "  Downloading uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.9.2 in /opt/conda/lib/python3.7/site-packages (from google-api-python-client==1.7.8) (0.20.2)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client==1.7.8) (4.8)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client==1.7.8) (4.2.4)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client==1.7.8) (0.2.7)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in /opt/conda/lib/python3.7/site-packages (from google-auth>=1.4.1->google-api-python-client==1.7.8) (59.6.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /opt/conda/lib/python3.7/site-packages (from httplib2<1dev,>=0.9.2->google-api-python-client==1.7.8) (3.0.6)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->google-api-python-client==1.7.8) (0.4.8)\n",
      "Installing collected packages: uritemplate, google-api-python-client\n",
      "  Attempting uninstall: uritemplate\n",
      "    Found existing installation: uritemplate 4.1.1\n",
      "    Uninstalling uritemplate-4.1.1:\n",
      "      Successfully uninstalled uritemplate-4.1.1\n",
      "  Attempting uninstall: google-api-python-client\n",
      "    Found existing installation: google-api-python-client 2.33.0\n",
      "    Uninstalling google-api-python-client-2.33.0:\n",
      "      Successfully uninstalled google-api-python-client-2.33.0\n",
      "Successfully installed google-api-python-client-1.7.8 uritemplate-3.0.1\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "2022-01-14 00:05:25,373\tINFO node.py:295 -- wait_for_compute_zone_operation: Waiting for operation operation-1642118724792-5d57f8f453237-7a8153a0-d9188025 to finish...\n",
      "2022-01-14 00:05:30,765\tINFO node.py:307 -- wait_for_compute_zone_operation: Operation operation-1642118724792-5d57f8f453237-7a8153a0-d9188025 finished.\n",
      "Cluster: sky-b1d1-ubuntu\n",
      "\n",
      "File Mount: (/tmp/setup.sh:/tmp/sky_setup_671171279.sh) refers to a file.\n",
      " To ensure this mount updates properly, please use a directory.\n",
      "Loaded cached provider configuration\n",
      "If you experience issues with the cloud provider, try re-running the command with --no-config-cache.\n",
      "Cluster Ray runtime will not be restarted due to `--no-restart`.\n",
      "Updating cluster configuration and running setup commands. Confirm [y/N]: y [automatic, due to --yes]\n",
      "\n",
      "<1/1> Setting up head node\n",
      "  Prepared bootstrap config\n",
      "  New status: waiting-for-ssh\n",
      "  [1/7] Waiting for SSH to become available\n",
      "    Running `uptime` as a test.\n",
      "    Fetched IP: 34.68.234.157\n",
      "    Success.\n",
      "  Updating cluster configuration. [hash=79204b8e5430c2d32522a8883bc378fb2068f8e9]\n",
      "  New status: syncing-files\n",
      "  [2/7] Processing file mounts\n",
      "    ~/.sky/remote_libs/ from /home/ubuntu/sky/prototype/sky/backends/remote_libs/\n",
      "    /tmp/setup.sh from /tmp/sky_setup_671171279.sh\n",
      "  [3/7] No worker file mounts to sync\n",
      "  New status: setting-up\n",
      "  [4/7] No initialization commands to run.\n",
      "  [5/7] Initalizing command runner\n",
      "  [6/7] Running setup commands\n",
      "    (0/4) pip3 install -U ray[default]==...\n",
      "    (1/4) pip3 install pendulum PrettyTa...\n",
      "    (2/4) cd ~/sky_workdir && bash /tmp/...\n",
      "    (3/4) pip install google-api-python-...\n",
      "  [7/7] Starting the Ray runtime\n",
      "  New status: up-to-date\n",
      "\n",
      "Useful commands\n",
      "  Monitor autoscaling with\n",
      "    ray exec /home/ubuntu/sky/prototype/config/user/sky-b1d1-ubuntu.yml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'\n",
      "  Connect to a terminal on the cluster head:\n",
      "    ray attach /home/ubuntu/sky/prototype/config/user/sky-b1d1-ubuntu.yml\n",
      "  Get a remote shell to the cluster manually:\n",
      "    ssh -o IdentitiesOnly=yes -i ~/.ssh/sky-key ubuntu@34.68.234.157\n",
      "\u001b[33mFile Mount: (/tmp/setup.sh:/tmp/sky_setup_671171279.sh) refers to a file.\n",
      " To ensure this mount updates properly, please use a directory.\u001b[39m\n",
      "2022-01-14 00:05:31,465\tINFO util.py:282 -- setting max workers for head node type to 0\n",
      "\u001b[33mLoaded cached provider configuration\u001b[39m\n",
      "\u001b[33mIf you experience issues with the cloud provider, try re-running the command with \u001b[1m--no-config-cache\u001b[22m\u001b[26m.\u001b[39m\n",
      "\u001b[37mFetched IP\u001b[39m: \u001b[1m34.68.234.157\u001b[22m\n",
      "Shared connection to 34.68.234.157 closed.\n",
      "\u001b[0mI 01-14 00:05:34 cloud_vm_ray_backend.py:700] \u001b[1mSuccessfully provisioned or found existing VM. Setup completed.\u001b[0m\n",
      "I 01-14 00:05:34 cloud_vm_ray_backend.py:703] \n",
      "I 01-14 00:05:34 cloud_vm_ray_backend.py:703] To log into the head VM:\t\u001b[1mssh sky-b1d1-ubuntu\u001b[0m\n",
      "I 01-14 00:05:34 cloud_vm_ray_backend.py:703] \n",
      "I 01-14 00:05:41 cloud_vm_ray_backend.py:1253] Reserved Job ID: 1\n",
      "I 01-14 00:05:43 cloud_vm_ray_backend.py:1375] \n",
      "I 01-14 00:05:43 cloud_vm_ray_backend.py:1375] \u001b[36mCluster name: \u001b[1msky-b1d1-ubuntu\u001b[0m\n",
      "I 01-14 00:05:43 cloud_vm_ray_backend.py:1375] To log into the head VM:\t\u001b[1mssh sky-b1d1-ubuntu\u001b[0m\n",
      "I 01-14 00:05:43 cloud_vm_ray_backend.py:1375] To submit a job:\t\t\u001b[1msky exec -c sky-b1d1-ubuntu yaml_file\u001b[0m\n",
      "I 01-14 00:05:43 cloud_vm_ray_backend.py:1375] To stop the cluster:\t\u001b[1msky stop sky-b1d1-ubuntu\u001b[0m\n",
      "I 01-14 00:05:43 cloud_vm_ray_backend.py:1375] To teardown the cluster:\t\u001b[1msky down sky-b1d1-ubuntu\u001b[0m\n",
      "I 01-14 00:05:43 cloud_vm_ray_backend.py:1390] Tip: `sky down` will delete launched TPU(s) too.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/sky/prototype/sky/execution.py\", line 133, in _execute\n",
      "    backend.execute(handle, task, detach_run)\n",
      "  File \"/home/ubuntu/sky/prototype/sky/backends/cloud_vm_ray_backend.py\", line 1276, in execute\n",
      "    return self._execute_task_one_node(handle, task, job_id, detach_run)\n",
      "  File \"/home/ubuntu/sky/prototype/sky/backends/cloud_vm_ray_backend.py\", line 1309, in _execute_task_one_node\n",
      "    self._exec_code_on_head(handle,\n",
      "  File \"/home/ubuntu/sky/prototype/sky/backends/cloud_vm_ray_backend.py\", line 1211, in _exec_code_on_head\n",
      "    self._run_command_on_head_via_ssh(handle,\n",
      "  File \"/home/ubuntu/sky/prototype/sky/backends/cloud_vm_ray_backend.py\", line 1538, in _run_command_on_head_via_ssh\n",
      "    return backend_utils.run_with_log(command,\n",
      "  File \"/home/ubuntu/sky/prototype/sky/backends/remote_libs/log_lib.py\", line 87, in run_with_log\n",
      "    raise RuntimeError('Command failed, please check the logs.')\n",
      "RuntimeError: Command failed, please check the logs.\n",
      "\n",
      "Sky Clusters\n",
      "+-----------------+----------------+-------------------------------------------+-----------------------------------+--------+\n",
      "|       NAME      |    LAUNCHED    |                 RESOURCES                 | COMMAND                           | STATUS |\n",
      "+-----------------+----------------+-------------------------------------------+-----------------------------------+--------+\n",
      "|   test-github   |   18 hrs ago   |             1x AWS(m4.2xlarge)            | sky cpunode -c test-github        |   UP   |\n",
      "| sky-bbbd-ubuntu |    1 hr ago    |             1x AWS(m4.2xlarge)            | sky launch /tmp/sky_tour-h_z1hu1m |   UP   |\n",
      "|      mycpu      |  29 mins ago   |             1x AWS(m4.2xlarge)            | sky cpunode -c mycpu              |   UP   |\n",
      "|    mycluster    |  20 mins ago   |             1x AWS(p2.xlarge)             | sky start mycluster               |   UP   |\n",
      "| sky-d2cd-ubuntu |   5 mins ago   |             1x AWS(p2.xlarge)             | sky launch /tmp/sky_tour-95vvfs_1 |  INIT  |\n",
      "| sky-b1d1-ubuntu | a few secs ago | 1x GCP(n1-highmem-8, {'tpu-v3-8': 1}, ... | sky launch -c sky-b1d1-ubuntu ... |   UP   |\n",
      "+-----------------+----------------+-------------------------------------------+-----------------------------------+--------+\n",
      "\u001b[0m\u001b[0m"
     ]
    }
   ],
   "source": [
    "!sky launch -c sky-b1d1-ubuntu $SKY_SPEC"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ec09e32e-7284-4d9d-9c0e-95551ee947c9",
   "metadata": {},
   "source": [
    "## Interative Development\n",
    "Sky also supports iterative development with the interactive nodes. Currently, GPU, CPU, and TPU (Google Cloud only) nodes are supported. They can be configured with a variety of options and support port forwarding, tmux, screen, and spot instances. We also enable native ssh support for all clusters for debugging and interactive development purposes.\n",
    "\n",
    "Try the following in your terminal!\n",
    "```\n",
    "sky gpunode -c mygpu --gpus K80 --cloud gcp\n",
    "```\n",
    "\n",
    "If you would like to temporarily stop a cluster, use `sky stop`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "36024db2-8771-4243-b2dd-b0cd3b281025",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mFile Mount: (/tmp/setup.sh:/tmp/sky_setup_2521886668.sh) refers to a file.\n",
      " To ensure this mount updates properly, please use a directory.\u001b[39m\n",
      "2022-01-13 23:37:35,689\tINFO util.py:282 -- setting max workers for head node type to 0\n",
      "\u001b[33mLoaded cached provider configuration\u001b[39m\n",
      "\u001b[33mIf you experience issues with the cloud provider, try re-running the command with \u001b[1m--no-config-cache\u001b[22m\u001b[26m.\u001b[39m\n",
      "Destroying cluster. \u001b[4mConfirm [y/N]:\u001b[24m y \u001b[2m[automatic, due to --yes]\u001b[22m\n",
      "\u001b[33mFile Mount: (/tmp/setup.sh:/tmp/sky_setup_2521886668.sh) refers to a file.\n",
      " To ensure this mount updates properly, please use a directory.\u001b[39m\n",
      "2022-01-13 23:37:35,777\tINFO util.py:282 -- setting max workers for head node type to 0\n",
      "\u001b[37mFetched IP\u001b[39m: \u001b[1m18.214.89.219\u001b[22m\n",
      "Warning: Permanently added '18.214.89.219' (ECDSA) to the list of known hosts.\n",
      "\u001b[32mStopped all 14 Ray processes.\u001b[39m\n",
      "\u001b[0mShared connection to 18.214.89.219 closed.\n",
      "Stopping instances \u001b[1mi-0a9ae425f8260dff1\u001b[22m \u001b[2m(to terminate instead, set `cache_stopped_nodes: False` under `provider` in the cluster configuration)\u001b[22m\n",
      "Requested \u001b[1m1\u001b[22m\u001b[26m nodes to shut down.\u001b[0m\u001b[2m [interval=1s]\u001b[22m\u001b[0m\n",
      "\u001b[1m0\u001b[22m\u001b[26m nodes remaining after 5 second(s).\n",
      "\u001b[32mNo nodes remaining.\u001b[39m\n",
      "\u001b[0m\u001b[32mStopping cluster mycluster...done.\u001b[0m\n",
      "  To restart the cluster, run: \u001b[1msky start mycluster\u001b[0m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!sky stop mycluster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "a892dad4-a820-413b-b7fc-939771479ed6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sky Clusters\n",
      "+-----------------+-------------+--------------------+-----------------------------------+--------+\n",
      "|       NAME      |   LAUNCHED  |     RESOURCES      | COMMAND                           | STATUS |\n",
      "+-----------------+-------------+--------------------+-----------------------------------+--------+\n",
      "|   test-github   |  18 hrs ago | 1x AWS(m4.2xlarge) | sky cpunode -c test-github        |   UP   |\n",
      "| sky-bbbd-ubuntu | 43 mins ago | 1x AWS(m4.2xlarge) | sky launch /tmp/sky_tour-h_z1hu1m |   UP   |\n",
      "|      mycpu      |  9 mins ago | 1x AWS(m4.2xlarge) | sky cpunode -c mycpu              |   UP   |\n",
      "|    mycluster    | 19 secs ago | 1x AWS(p2.xlarge)  | sky start mycluster               |   UP   |\n",
      "+-----------------+-------------+--------------------+-----------------------------------+--------+\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!sky status"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c24a3aea-a9ce-4f9b-ba76-8b4f6e6f184f",
   "metadata": {},
   "source": [
    "To restart the cluster, use `sky start`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "8fd0e611-4622-4840-bda5-b968634ef242",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1mStarting cluster mycluster...\u001b[0m\n",
      "I 01-13 23:41:55 cloud_vm_ray_backend.py:624] To view detailed progress: \u001b[1mtail -n100 -f sky_logs/sky-2022-01-13-23-41-55-979318/provision.log\u001b[0m\n",
      "I 01-13 23:41:55 cloud_vm_ray_backend.py:634] \n",
      "I 01-13 23:41:55 cloud_vm_ray_backend.py:634] \u001b[1mLaunching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f)\u001b[0m\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Requirement already satisfied: ray[default]==1.9.2 in ./.local/lib/python3.6/site-packages (1.9.2)\n",
      "Requirement already satisfied: dataclasses in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (0.8)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (1.0.3)\n",
      "Requirement already satisfied: redis>=3.5.0 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (4.1.0)\n",
      "Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (5.4.1)\n",
      "Requirement already satisfied: jsonschema in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (3.2.0)\n",
      "Requirement already satisfied: grpcio>=1.28.1 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (1.43.0)\n",
      "Requirement already satisfied: attrs in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (21.2.0)\n",
      "Requirement already satisfied: filelock in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (3.4.1)\n",
      "Requirement already satisfied: protobuf>=3.15.3 in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (3.18.1)\n",
      "Requirement already satisfied: click>=7.0 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (8.0.3)\n",
      "Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (1.19.5)\n",
      "Requirement already satisfied: py-spy>=0.2.0 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (0.3.11)\n",
      "Requirement already satisfied: prometheus-client>=0.7.1 in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (0.11.0)\n",
      "Requirement already satisfied: smart-open in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (5.2.1)\n",
      "Requirement already satisfied: aiosignal in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (1.2.0)\n",
      "Requirement already satisfied: aiohttp>=3.7 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (3.8.1)\n",
      "Requirement already satisfied: frozenlist in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (1.2.0)\n",
      "Requirement already satisfied: gpustat>=1.0.0b1 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (1.0.0b1)\n",
      "Requirement already satisfied: aioredis<2 in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (1.3.1)\n",
      "Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from ray[default]==1.9.2) (2.26.0)\n",
      "Requirement already satisfied: opencensus in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (0.8.0)\n",
      "Requirement already satisfied: aiohttp-cors in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (0.7.0)\n",
      "Requirement already satisfied: colorful in ./.local/lib/python3.6/site-packages (from ray[default]==1.9.2) (0.5.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in ./.local/lib/python3.6/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (1.7.2)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.6/dist-packages (from aiohttp>=3.7->ray[default]==1.9.2) (3.10.0.2)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in ./.local/lib/python3.6/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (5.2.0)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.local/lib/python3.6/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (4.0.2)\n",
      "Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp>=3.7->ray[default]==1.9.2) (2.0.6)\n",
      "Requirement already satisfied: idna-ssl>=1.0 in ./.local/lib/python3.6/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (1.1.0)\n",
      "Requirement already satisfied: asynctest==0.13.0 in ./.local/lib/python3.6/site-packages (from aiohttp>=3.7->ray[default]==1.9.2) (0.13.0)\n",
      "Requirement already satisfied: hiredis in ./.local/lib/python3.6/site-packages (from aioredis<2->ray[default]==1.9.2) (2.0.0)\n",
      "Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from click>=7.0->ray[default]==1.9.2) (4.8.1)\n",
      "Requirement already satisfied: nvidia-ml-py3>=7.352.0 in ./.local/lib/python3.6/site-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (7.352.0)\n",
      "Requirement already satisfied: psutil in ./.local/lib/python3.6/site-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (5.9.0)\n",
      "Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.6/dist-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (1.16.0)\n",
      "Requirement already satisfied: blessed>=1.17.1 in ./.local/lib/python3.6/site-packages (from gpustat>=1.0.0b1->ray[default]==1.9.2) (1.19.0)\n",
      "Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.6/dist-packages (from blessed>=1.17.1->gpustat>=1.0.0b1->ray[default]==1.9.2) (0.2.5)\n",
      "Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.6/dist-packages (from idna-ssl>=1.0->aiohttp>=3.7->ray[default]==1.9.2) (3.2)\n",
      "Requirement already satisfied: packaging>=21.3 in ./.local/lib/python3.6/site-packages (from redis>=3.5.0->ray[default]==1.9.2) (21.3)\n",
      "Requirement already satisfied: deprecated>=1.2.3 in ./.local/lib/python3.6/site-packages (from redis>=3.5.0->ray[default]==1.9.2) (1.2.13)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.6/dist-packages (from deprecated>=1.2.3->redis>=3.5.0->ray[default]==1.9.2) (1.12.1)\n",
      "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->click>=7.0->ray[default]==1.9.2) (3.6.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging>=21.3->redis>=3.5.0->ray[default]==1.9.2) (2.4.7)\n",
      "Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/dist-packages (from jsonschema->ray[default]==1.9.2) (0.18.0)\n",
      "Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from jsonschema->ray[default]==1.9.2) (58.2.0)\n",
      "Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in ./.local/lib/python3.6/site-packages (from opencensus->ray[default]==1.9.2) (2.4.0)\n",
      "Requirement already satisfied: opencensus-context==0.1.2 in ./.local/lib/python3.6/site-packages (from opencensus->ray[default]==1.9.2) (0.1.2)\n",
      "Requirement already satisfied: contextvars in ./.local/lib/python3.6/site-packages (from opencensus-context==0.1.2->opencensus->ray[default]==1.9.2) (2.4)\n",
      "Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in ./.local/lib/python3.6/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (2.3.3)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in ./.local/lib/python3.6/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (1.54.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.6/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (4.7.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/lib/python3/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (0.2.1)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./.local/lib/python3.6/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (4.2.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->ray[default]==1.9.2) (1.26.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->ray[default]==1.9.2) (2021.5.30)\n",
      "Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from rsa<5,>=3.1.4->google-auth<3.0dev,>=1.25.0->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]==1.9.2) (0.4.8)\n",
      "Requirement already satisfied: immutables>=0.9 in ./.local/lib/python3.6/site-packages (from contextvars->opencensus-context==0.1.2->opencensus->ray[default]==1.9.2) (0.16)\n",
      "\u001b[33mWARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Requirement already satisfied: pendulum in ./.local/lib/python3.6/site-packages (2.1.2)\n",
      "Requirement already satisfied: PrettyTable in ./.local/lib/python3.6/site-packages (2.5.0)\n",
      "Requirement already satisfied: python-dateutil<3.0,>=2.6 in /usr/local/lib/python3.6/dist-packages (from pendulum) (2.8.2)\n",
      "Requirement already satisfied: pytzdata>=2020.1 in ./.local/lib/python3.6/site-packages (from pendulum) (2020.1)\n",
      "Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from PrettyTable) (4.8.1)\n",
      "Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from PrettyTable) (0.2.5)\n",
      "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil<3.0,>=2.6->pendulum) (1.16.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->PrettyTable) (3.6.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->PrettyTable) (3.10.0.2)\n",
      "\u001b[33mWARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.\n",
      "You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Requirement already satisfied: boto3>=1.4.8 in /usr/local/lib/python2.7/dist-packages (1.17.112)\n",
      "Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.4.8) (0.10.0)\n",
      "Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.4.8) (0.4.2)\n",
      "Requirement already satisfied: botocore<1.21.0,>=1.20.112 in /usr/local/lib/python2.7/dist-packages (from boto3>=1.4.8) (1.20.112)\n",
      "Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == \"2.7\" in /usr/local/lib/python2.7/dist-packages (from s3transfer<0.5.0,>=0.4.0->boto3>=1.4.8) (3.3.0)\n",
      "Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python2.7/dist-packages (from botocore<1.21.0,>=1.20.112->boto3>=1.4.8) (2.8.2)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python2.7/dist-packages (from botocore<1.21.0,>=1.20.112->boto3>=1.4.8) (1.26.7)\n",
      "Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.21.0,>=1.20.112->boto3>=1.4.8) (1.16.0)\n",
      "\u001b[33mWARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Did not find any active Ray processes.\n",
      "\u001b[0mbash: ulimit: open files: cannot modify limit: Operation not permitted\n",
      "\u001b[37mLocal node IP\u001b[39m: \u001b[1m172.31.60.142\u001b[22m\n",
      "2022-01-13 23:44:55,700\tINFO services.py:1340 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "\n",
      "\u001b[32m--------------------\u001b[39m\n",
      "\u001b[32mRay runtime started.\u001b[39m\n",
      "\u001b[32m--------------------\u001b[39m\n",
      "\n",
      "\u001b[36mNext steps\u001b[39m\n",
      "  To connect to this Ray runtime from another node, run\n",
      "  \u001b[1m  ray start --address='172.31.60.142:6379' --redis-password='5241590000000000'\u001b[22m\n",
      "  \n",
      "  Alternatively, use the following Python code:\n",
      "    \u001b[31mimport\u001b[39m\u001b[26m ray\n",
      "    ray\u001b[31m.\u001b[39m\u001b[26minit(address\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'auto'\u001b[39m\u001b[26m, _redis_password\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'5241590000000000'\u001b[39m\u001b[26m)\n",
      "  \n",
      "  To connect to this Ray runtime from outside of the cluster, for example to\n",
      "  connect to a remote cluster from your laptop directly, use the following\n",
      "  Python code:\n",
      "    \u001b[31mimport\u001b[39m\u001b[26m ray\n",
      "    ray\u001b[31m.\u001b[39m\u001b[26minit(address\u001b[31m=\u001b[39m\u001b[26m\u001b[33m'ray://<head_node_ip_address>:10001'\u001b[39m\u001b[26m)\n",
      "  \n",
      "  \u001b[4mIf connection fails, check your firewall settings and network configuration.\u001b[24m\n",
      "  \n",
      "  To terminate the Ray runtime, run\n",
      "  \u001b[1m  ray stop\u001b[22m\n",
      "\u001b[0mCluster: mycluster\n",
      "Shared connection to 54.146.90.55 closed.\n",
      "\n",
      "Checking AWS environment settings\n",
      "AWS config\n",
      "  IAM Profile: ray-autoscaler-v1 [default]\n",
      "  EC2 Key pair (all available node types): sky-key-61ef58\n",
      "  VPC Subnets (all available node types): subnet-fca11d9a, subnet-822893a3, subnet-9dcd81d0, subnet-254bf27a, subnet-1a78b82b, subnet-cb92e4c5 [default]\n",
      "  EC2 Security groups (all available node types): sg-0cd6f7480591cd6ad [default]\n",
      "  EC2 AMI (all available node types): ami-0e3c68b57d50caf64\n",
      "\n",
      "No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]\n",
      "\n",
      "Acquiring an up-to-date head node\n",
      "  Reusing nodes i-0a9ae425f8260dff1. To disable reuse, set `cache_stopped_nodes: False` under `provider` in the cluster configuration.\n",
      "  Stopping instances to reuse\n",
      "    Waiting for instance i-0a9ae425f8260dff1 to stop\n",
      "  Launched a new head node\n",
      "  Fetching the new head node\n",
      "  \n",
      "<1/1> Setting up head node\n",
      "  Prepared bootstrap config\n",
      "  New status: waiting-for-ssh\n",
      "  [1/7] Waiting for SSH to become available\n",
      "    Running `uptime` as a test.\n",
      "    Waiting for IP\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Not yet available, retrying in 5 seconds\n",
      "      Received: 54.146.90.55\n",
      "    SSH still not available (SSH command failed.), retrying in 5 seconds.\n",
      "    SSH still not available (SSH command failed.), retrying in 5 seconds.\n",
      "    Success.\n",
      "  Updating cluster configuration. [hash=d05dccb91f8c6e93cae5b09f894ae13214c989fd]\n",
      "  New status: syncing-files\n",
      "  [2/7] Processing file mounts\n",
      "    ~/.sky/remote_libs/ from /home/ubuntu/sky/prototype/sky/backends/remote_libs/\n",
      "  [3/7] No worker file mounts to sync\n",
      "  New status: setting-up\n",
      "  [4/7] No initialization commands to run.\n",
      "  [5/7] Initalizing command runner\n",
      "  [6/7] Running setup commands\n",
      "    (0/3) pip3 install -U ray[default]==...\n",
      "    (1/3) pip3 install pendulum PrettyTa...\n",
      "    (2/3) pip install 'boto3>=1.4.8'\n",
      "  [7/7] Starting the Ray runtime\n",
      "  New status: up-to-date\n",
      "\n",
      "Useful commands\n",
      "  Monitor autoscaling with\n",
      "    ray exec /home/ubuntu/sky/prototype/config/user/mycluster.yml 'tail -n 100 -f /tmp/ray/session_latest/logs/monitor*'\n",
      "  Connect to a terminal on the cluster head:\n",
      "    ray attach /home/ubuntu/sky/prototype/config/user/mycluster.yml\n",
      "  Get a remote shell to the cluster manually:\n",
      "    ssh -o IdentitiesOnly=yes -i ~/.ssh/sky-key ubuntu@54.146.90.55\n",
      "I 01-13 23:44:58 cloud_vm_ray_backend.py:700] \u001b[1mSuccessfully provisioned or found existing VM. Setup completed.\u001b[0m\n",
      "I 01-13 23:44:58 cloud_vm_ray_backend.py:703] \n",
      "I 01-13 23:44:58 cloud_vm_ray_backend.py:703] To log into the head VM:\t\u001b[1mssh mycluster\u001b[0m\n",
      "I 01-13 23:44:58 cloud_vm_ray_backend.py:703] \n",
      "\u001b[32mCluster mycluster started.\u001b[0m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!sky start mycluster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "68550ecc-a2ec-4e97-a884-21330e19ffb5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sky Clusters\n",
      "+-----------------+----------------+--------------------+-----------------------------------+--------+\n",
      "|       NAME      |    LAUNCHED    |     RESOURCES      | COMMAND                           | STATUS |\n",
      "+-----------------+----------------+--------------------+-----------------------------------+--------+\n",
      "|   test-github   |   18 hrs ago   | 1x AWS(m4.2xlarge) | sky cpunode -c test-github        |   UP   |\n",
      "| sky-bbbd-ubuntu |  43 mins ago   | 1x AWS(m4.2xlarge) | sky launch /tmp/sky_tour-h_z1hu1m |   UP   |\n",
      "|      mycpu      |   9 mins ago   | 1x AWS(m4.2xlarge) | sky cpunode -c mycpu              |   UP   |\n",
      "|    mycluster    | a few secs ago | 1x AWS(p2.xlarge)  | sky start mycluster               |   UP   |\n",
      "+-----------------+----------------+--------------------+-----------------------------------+--------+\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!sky status"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "552bd643-33a6-4d91-a81e-6df521e4fe65",
   "metadata": {},
   "source": [
    "## Sky Storage"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "id": "737da390-56fc-44af-9c02-b2f2d57295c6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Should probably get its own set of docs. \n",
    "# A bit hard to show in jupyter walkthrough unless we have local mounts?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4ecd7c80-e774-471d-bd90-f5bf7f2e000a",
   "metadata": {},
   "source": [
    "## Python API\n",
    "For advanced use cases, we allow users to automate worfklows with Sky using our Python API."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75d841ef-c1d0-4c62-b503-34a313fed2a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "I 01-14 00:07:15 execution.py:83] Optimizer target is set to COST.\n",
      "I 01-14 00:07:15 optimizer.py:208] Defaulting estimated time to 1 hr. Call Task.set_time_estimator() to override.\n",
      "I 01-14 00:07:15 optimizer.py:307] Optimizer - plan minimizing cost (~$3.1):\n",
      "I 01-14 00:07:15 optimizer.py:321] \n",
      "I 01-14 00:07:15 optimizer.py:321] TASK    BEST_RESOURCE\n",
      "I 01-14 00:07:15 optimizer.py:321] ping    AWS(p3.2xlarge)\n",
      "I 01-14 00:07:15 optimizer.py:321] \n",
      "I 01-14 00:07:15 cloud_vm_ray_backend.py:993] \u001b[36mCreating a new cluster: \"sky-d83a-ubuntu\" [1x AWS(p3.2xlarge)].\u001b[0m\n",
      "I 01-14 00:07:15 cloud_vm_ray_backend.py:993] Tip: to reuse an existing cluster, specify --cluster-name (-c) in the CLI or use sky.launch(.., cluster_name=..) in the Python API. Run `sky status` to see existing clusters.\n",
      "I 01-14 00:07:15 cloud_vm_ray_backend.py:624] To view detailed progress: \u001b[1mtail -n100 -f sky_logs/sky-2022-01-14-00-07-15-794515/provision.log\u001b[0m\n",
      "I 01-14 00:07:15 cloud_vm_ray_backend.py:634] \n",
      "I 01-14 00:07:15 cloud_vm_ray_backend.py:634] \u001b[1mLaunching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e,us-east-1f)\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "import sky\n",
    "\n",
    "backend = sky.backends.CloudVmRayBackend()\n",
    "\n",
    "with sky.Dag() as dag:\n",
    "    resources = sky.Resources(cloud=sky.AWS(), accelerators={'V100': 1})\n",
    "    setup_commands = 'echo \"Hello, Sky!\"'\n",
    "    task = sky.Task(run='ping 127.0.0.1 -c 5',\n",
    "                    setup=setup_commands,\n",
    "                    name='ping').set_resources(resources)\n",
    "\n",
    "sky.launch(dag, backend=backend)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "232323d8-ee37-4744-9022-12225fa5cffe",
   "metadata": {},
   "source": [
    "#### Check out our example YAML specs and Python scripts under `prototype/examples/` to get started! "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
